# Generated by Django 3.2.5 on 2021-07-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default=None, max_length=5)),
                ('area', models.IntegerField(default=None)),
                ('price', models.FloatField(default=None)),
                ('image', models.ImageField(upload_to='')),
                ('view', models.CharField(default=None, max_length=20)),
                ('lat_coord', models.FloatField(default=None)),
                ('lng_coord', models.FloatField(default=None)),
                ('bedrooms', models.IntegerField(default=None)),
                ('livingrooms', models.IntegerField(default=None)),
            ],
        ),
    ]
