# Generated by Django 3.2.5 on 2022-02-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
